### ISSUE TITLE
[BUG] unsupported widget type asrc when run build-tools.sh

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof#2543]
The SND_SOC_TPLG_DAPM_ASRC is delete from upstream alsa-lib(`src/topology/damp.c: line24~line48`), so topologies contain ASRC component will be failed to build. we got :`widget 'ASRC1.0': unsupported widget type asrc` error when run build-tools.sh.

alsa-lib commit which makes the change: https://github.com/alsa-project/alsa-lib/commit/aa1bac2d04bd1fb4ccae96a1136e60454298a710

**Comment by aiChaoSONG** [comment]
@lgirdwood @plbossart What are we going to do with this?

**Comment by lgirdwood** [comment]
@aiChaoSONG can you bisect to see when this was removed and who did it ?

**Comment by tlauda** [comment]
@lgirdwood It's already in the bug: 
> alsa-lib commit which makes the change: alsa-project/alsa-lib@aa1bac2

**Comment by plbossart** [comment]
@aiChaoSONG Sorry I don't get what you meant by 'delete from upstream'. It was never added?

@singalsu you've added those topologies with ASRC, did you face any issues with alsa-lib?

**Comment by singalsu** [comment]
I haven't got this issue. I've run tools build with various recent Ubuntu Linuxes. There has no more been need to use alsa tools git version to create SOF topologies.

Why is ASRC being removed from ALSA?

**Comment by tlauda** [comment]
> I haven't got this issue. I've run tools build with various recent Ubuntu Linuxes. There has no more been need to use alsa tools git version to create SOF topologies.
> 
> Why is ASRC being removed from ALSA?

It looks like some kind of accidental removal?
Maybe @perexg could elaborate.

**Comment by perexg** [comment]
Yep, it's accidental removal. Fixed in alsa-lib's master. Thanks for the note.

**Comment by marc-hb** [comment]
FWIW reproduced with out-of-the-box alsa-lib 1.2.2-1.fc31

**Comment by marc-hb** [comment]
While no release include the v1.2.2-6-gcaf77a93cef5 fix yet, it has been cherry-picked in the `alsa-git.patch` of alsa-utils version 1.2.2 **-2** .fc31 https://koji.fedoraproject.org/koji/rpminfo?rpmID=21111550

On Ubuntu 20.04, alsa-utils 1.2.2-1ubuntu1 does not have this fix.

**Comment by marc-hb** [comment]
Here's a quick, dirty and lazy workaround for this situation: 

```shell
# Remove asrc from ALG_MODE_TESTS list
sed -i -e '/^ALG_MODE_TESTS=.*asrc/ s/asrc//' tools/test/topology/tplg-build.sh 

# Comment out all lines with 'asrc'
sed -i -e '/asrc/ s/.*/# &/' tools/topology/CMakeLists.txt

git commit -m -n 'HACK: disable ASRC1.0' tools/test/topology/tplg-build.sh  tools/topology/CMakeLists.txt
```
See PR `scripts: build-tools.sh: Make tools individually buildable` #3064 for more background

**Comment by marc-hb** [comment]
Fix still not cherry-picked by Ubuntu 20.04 in `libatopology2 1.2.2-2.1ubuntu2`
